id: P000297
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG13001
  title: བསྙུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    4873752bb97b42df8009b1719fc62e2b:
      image_group_id: I1KG13066
      title: Volume 1 of bsnyung gnas kyi rnam bshad dang phan yon skor phyogs bsgrigs/
      volume_number: 1
      total_pages: 408
      base_file: v001.txt
